/*
  THE THIRD POSITION — Dilemma Bank
  ---------------------------------
  Each dilemma:
    id            unique string, stable forever (never renumber existing ids)
    domain        one of DOMAINS (see below)
    positionA/B   two genuinely defensible, opposing positions (not fake opposites)
    tension       (hidden until after answering) the underlying tension in one line
    constructs    (hidden) deeper constructs this dilemma probes
    family        (hidden) structural family id — used to find twins
    twinGroup     (hidden) id shared by dilemmas that are structural twins of each other,
                  even though they look unrelated on the surface. Omit if none.
    notes         (hidden) optional free note for future-you

  To add your own dilemmas later: append objects to this array following the
  same shape. Ids should be unique strings. If you want a new dilemma to be a
  structural twin of an existing one, reuse that dilemma's twinGroup value.
  Nothing else in the app needs to change — the dilemma bank is the only file
  you need to touch to add material.
*/

const DOMAINS = [
  "knowledge & evidence",
  "relationships",
  "autonomy",
  "morality",
  "creativity",
  "classification",
  "identity",
  "memory",
  "uncertainty",
  "decision-making",
  "social interpretation",
  "responsibility",
  "rules & exceptions",
  "order & spontaneity",
  "emotional reasoning",
  "aesthetics",
  "trust",
  "change & continuity",
];

const DILEMMAS = [
  // ---------- knowledge & evidence ----------
  {
    id: "d001",
    domain: "knowledge & evidence",
    positionA: "Keep researching until the contradictions in the evidence are resolved.",
    positionB: "Act on the strongest available evidence despite unresolved uncertainty.",
    tension: "when accumulated evidence becomes sufficient grounds for action",
    constructs: ["sufficiency vs completeness", "provisional commitment"],
    family: "SUFFICIENCY_TO_COMMIT",
    twinGroup: "TWIN_SUFFICIENCY",
  },
  {
    id: "d002",
    domain: "knowledge & evidence",
    positionA: "A claim should be believed only once it can survive your strongest attempt to disprove it.",
    positionB: "Demanding constant disproof of everything you believe makes ordinary life impossible.",
    tension: "how much scrutiny a belief needs before it can be used",
    constructs: ["falsifiability", "practical belief vs rigorous belief"],
    family: "SCRUTINY_CALIBRATION",
  },
  {
    id: "d003",
    domain: "knowledge & evidence",
    positionA: "If an expert consensus exists, deferring to it is the rational choice for a non-expert.",
    positionB: "Outsourcing your judgment to consensus is how bad consensus survives unchallenged.",
    tension: "when deference to authority is reasonable vs abdication",
    constructs: ["epistemic authority", "independent verification"],
    family: "AUTHORITY_VS_INDEPENDENCE",
    twinGroup: "TWIN_AUTHORITY",
  },
  {
    id: "d004",
    domain: "knowledge & evidence",
    positionA: "A single well-documented counterexample should be enough to break a general rule.",
    positionB: "One anomaly does not outweigh a pattern built from hundreds of consistent cases.",
    tension: "how much weight an anomaly deserves against an established pattern",
    constructs: ["exception handling", "base rate vs case"],
    family: "RULE_VS_EXCEPTION",
  },
  {
    id: "d005",
    domain: "knowledge & evidence",
    positionA: "You don't really understand something until you can rebuild it from first principles.",
    positionB: "Requiring first-principles understanding of everything you use would make you unable to function.",
    tension: "how deep understanding needs to go before it counts as understanding",
    constructs: ["depth vs functional competence"],
    family: "DEPTH_THRESHOLD",
  },

  // ---------- relationships ----------
  {
    id: "d006",
    domain: "relationships",
    positionA: "You should tell people hard truths even when they haven't asked for them.",
    positionB: "Volunteering unrequested truths is often more about your need to say them than their need to hear them.",
    tension: "when honesty serves the other person vs the speaker",
    constructs: ["consent to be told", "self-serving honesty"],
    family: "SELF_VS_OTHER_SERVING",
  },
  {
    id: "d007",
    domain: "relationships",
    positionA: "Real closeness means being fully known, including the parts that aren't flattering.",
    positionB: "Everyone is entitled to keep some rooms of themselves closed, even from people they love.",
    tension: "how much disclosure intimacy actually requires",
    constructs: ["privacy vs intimacy", "autonomy within closeness"],
    family: "AUTONOMY_VS_CARE",
    twinGroup: "TWIN_AUTONOMY_CARE",
  },
  {
    id: "d008",
    domain: "relationships",
    positionA: "When trust is broken, the relationship should be rebuilt from scratch, on new terms.",
    positionB: "A relationship's history is worth more than the terms of a fresh start; repair should build on what existed.",
    tension: "whether trust repair is reconstruction or renegotiation",
    constructs: ["continuity vs reset", "repair mechanisms"],
    family: "PRESERVATION_VS_REVISION",
  },
  {
    id: "d009",
    domain: "relationships",
    positionA: "You should give people the benefit of the doubt until they clearly prove otherwise.",
    positionB: "Extending trust by default is how the same people keep getting away with the same harm.",
    tension: "the default posture toward an unproven accusation of harm",
    constructs: ["default trust", "pattern recognition vs presumption"],
    family: "TRUST_DEFAULT",
    twinGroup: "TWIN_TRUST_DEFAULT",
  },
  {
    id: "d010",
    domain: "relationships",
    positionA: "Loyalty means standing by someone even when you think they're wrong.",
    positionB: "Standing by someone you believe is wrong is not loyalty, it's complicity dressed up.",
    tension: "what loyalty actually obligates you to do",
    constructs: ["loyalty vs honesty", "complicity"],
    family: "LOYALTY_VS_TRUTH",
  },

  // ---------- autonomy ----------
  {
    id: "d011",
    domain: "autonomy",
    positionA: "People have the right to make choices you're certain will hurt them.",
    positionB: "Watching someone you can help walk into harm and calling it 'their choice' is a way of avoiding responsibility.",
    tension: "where the right to self-determination ends and duty to intervene begins",
    constructs: ["paternalism", "consent vs harm"],
    family: "AUTONOMY_VS_CARE",
    twinGroup: "TWIN_AUTONOMY_CARE",
  },
  {
    id: "d012",
    domain: "autonomy",
    positionA: "Independence means making your major life decisions without needing anyone's approval.",
    positionB: "Nobody's decisions are really independent; pretending otherwise just hides who you're actually accountable to.",
    tension: "whether independence is a real state or a useful fiction",
    constructs: ["interdependence", "accountability"],
    family: "INDEPENDENCE_MYTH",
  },
  {
    id: "d013",
    domain: "autonomy",
    positionA: "A rule you impose on yourself only counts as discipline if you'd enforce it even when no one is watching.",
    positionB: "Self-discipline that never bends to circumstance is just rigidity wearing a better name.",
    tension: "whether self-imposed rules should be unconditional",
    constructs: ["self-governance", "flexibility vs integrity"],
    family: "RULE_VS_EXCEPTION",
  },
  {
    id: "d014",
    domain: "autonomy",
    positionA: "Freedom is the absence of constraints on your choices.",
    positionB: "Freedom is having the capability to actually act on your choices, constraints or not.",
    tension: "negative freedom (non-interference) vs positive freedom (capability)",
    constructs: ["negative vs positive liberty"],
    family: "FREEDOM_DEFINITION",
  },

  // ---------- morality ----------
  {
    id: "d015",
    domain: "morality",
    positionA: "Understanding why someone behaved badly is necessary for fair judgment.",
    positionB: "Explaining harmful behavior can quietly become excusing it.",
    tension: "whether causal explanation and moral excuse can be kept separate",
    constructs: ["explanation vs excuse", "intent vs impact"],
    family: "EXPLANATION_VS_EXCUSE",
    twinGroup: "TWIN_EXPLANATION_EXCUSE",
  },
  {
    id: "d016",
    domain: "morality",
    positionA: "What matters morally is the outcome of an action, not what the person intended.",
    positionB: "What matters morally is what the person intended, because outcomes are often outside their control.",
    tension: "consequences vs intentions as the unit of moral evaluation",
    constructs: ["intent vs outcome"],
    family: "INTENT_VS_OUTCOME",
  },
  {
    id: "d017",
    domain: "morality",
    positionA: "Some acts are wrong regardless of the consequences they produce.",
    positionB: "Whether an act is wrong depends entirely on the consequences it produces in context.",
    tension: "deontological vs consequentialist grounding",
    constructs: ["moral absolutism vs contextualism"],
    family: "RULE_VS_EXCEPTION",
  },
  {
    id: "d018",
    domain: "morality",
    positionA: "You are responsible for the direct, foreseeable effects of your actions and nothing more.",
    positionB: "You are responsible for the ripple effects of your actions even when you couldn't have predicted every one.",
    tension: "the boundary of moral responsibility for consequences",
    constructs: ["foreseeability", "scope of responsibility"],
    family: "INDIVIDUAL_VS_SYSTEM_RESPONSIBILITY",
    twinGroup: "TWIN_RESPONSIBILITY_SCOPE",
  },
  {
    id: "d019",
    domain: "morality",
    positionA: "Forgiveness should be something the wrongdoer earns through change.",
    positionB: "Forgiveness that waits on the wrongdoer's change gives them control over your peace.",
    tension: "whether forgiveness is conditional on the other person",
    constructs: ["conditional vs unconditional release"],
    family: "CONDITIONAL_VS_UNCONDITIONAL",
  },

  // ---------- creativity ----------
  {
    id: "d020",
    domain: "creativity",
    positionA: "A creative work should keep being revised until it matches the vision in your head.",
    positionB: "At some point, continuing to revise a creative work does more harm to it than good.",
    tension: "when a creative decision should stop being revised",
    constructs: ["provisional commitment", "diminishing returns of revision"],
    family: "SUFFICIENCY_TO_COMMIT",
    twinGroup: "TWIN_SUFFICIENCY",
  },
  {
    id: "d021",
    domain: "creativity",
    positionA: "Good creative work follows learnable rules of craft.",
    positionB: "Rules of craft are just a description of what worked before; real creative work breaks them.",
    tension: "craft as constraint vs craft as description",
    constructs: ["rule vs exception", "convention vs originality"],
    family: "RULE_VS_EXCEPTION",
  },
  {
    id: "d022",
    domain: "creativity",
    positionA: "The best creative work comes from structured process: outlines, drafts, deliberate technique.",
    positionB: "The best creative work comes from letting go of process and following impulse where it leads.",
    tension: "structure vs spontaneity as the source of good work",
    constructs: ["planning vs improvisation"],
    family: "STRUCTURE_VS_SPONTANEITY",
    twinGroup: "TWIN_STRUCTURE_SPONTANEITY",
  },
  {
    id: "d023",
    domain: "creativity",
    positionA: "A creator's intentions are the final authority on what a work means.",
    positionB: "Once a work is released, its meaning belongs to whoever encounters it, not to its creator.",
    tension: "authorial intent vs audience interpretation",
    constructs: ["ownership of meaning"],
    family: "OBSERVATION_VS_INTERPRETATION",
  },

  // ---------- classification ----------
  {
    id: "d024",
    domain: "classification",
    positionA: "Categories should be sharp enough that anything either clearly belongs or clearly doesn't.",
    positionB: "Forcing sharp boundaries onto naturally fuzzy categories distorts more than it clarifies.",
    tension: "whether category boundaries should be crisp or fuzzy",
    constructs: ["classification precision vs fidelity to reality"],
    family: "CATEGORY_SHARPNESS",
  },
  {
    id: "d025",
    domain: "classification",
    positionA: "A single exception that breaks a category system means the system needs to be redesigned.",
    positionB: "A category system that has to be redesigned for every exception was never useful to begin with.",
    tension: "how much a taxonomy should bend to edge cases",
    constructs: ["taxonomy stability", "edge-case tolerance"],
    family: "RULE_VS_EXCEPTION",
  },
  {
    id: "d026",
    domain: "classification",
    positionA: "Something should be classified by what it does, not by what it's called or where it came from.",
    positionB: "Origin and history are part of what a thing is, not incidental facts you can classify around.",
    tension: "function vs origin as the basis of identity",
    constructs: ["essentialism vs functionalism"],
    family: "FUNCTION_VS_ORIGIN",
    twinGroup: "TWIN_FUNCTION_ORIGIN",
  },
  {
    id: "d027",
    domain: "classification",
    positionA: "If most people agree on what a word means, that usage is what the word means.",
    positionB: "Popular usage of a word can be simply wrong relative to what the word precisely denotes.",
    tension: "descriptive vs prescriptive meaning",
    constructs: ["consensus vs precision"],
    family: "CONSENSUS_VS_PRECISION",
  },

  // ---------- identity ----------
  {
    id: "d028",
    domain: "identity",
    positionA: "If someone has genuinely changed, holding their past self against them is unfair.",
    positionB: "A person's past actions remain part of who they are, no matter how much they've changed since.",
    tension: "whether change dissolves accountability for who you were",
    constructs: ["continuity of self", "accountability across time"],
    family: "CONTINUITY_VS_CHANGE_IDENTITY",
    twinGroup: "TWIN_CONTINUITY_IDENTITY",
  },
  {
    id: "d029",
    domain: "identity",
    positionA: "Who you are is defined by the choices you consistently make, not by what you privately believe.",
    positionB: "Who you are includes private beliefs and desires even when circumstances never let you act on them.",
    tension: "identity as action vs identity as inner state",
    constructs: ["behavioral vs internal self"],
    family: "ACTION_VS_INNER_STATE",
  },
  {
    id: "d030",
    domain: "identity",
    positionA: "You should be essentially the same person across every context you're in.",
    positionB: "Adapting who you are to different contexts is not inconsistency, it's fluency.",
    tension: "cross-context consistency vs contextual adaptation",
    constructs: ["consistency vs adaptability"],
    family: "CONTEXT_DEPENDENCE",
    twinGroup: "TWIN_CONTEXT_DEPENDENCE",
  },
  {
    id: "d031",
    domain: "identity",
    positionA: "The labels you choose for yourself should be taken as authoritative by others.",
    positionB: "Self-description is one input among several; other people's observation of you also carries evidence.",
    tension: "first-person authority vs third-person observation about identity",
    constructs: ["self-report vs observed pattern"],
    family: "OBSERVATION_VS_INTERPRETATION",
  },

  // ---------- memory ----------
  {
    id: "d032",
    domain: "memory",
    positionA: "A memory you can no longer verify should be treated with the same weight as one you can.",
    positionB: "An unverifiable memory should be held more loosely than a documented one, however vivid it feels.",
    tension: "phenomenological certainty vs verifiability",
    constructs: ["confidence vs accuracy", "vividness as evidence"],
    family: "SCRUTINY_CALIBRATION",
  },
  {
    id: "d033",
    domain: "memory",
    positionA: "You should trust your present memory of an event over someone else's differing account.",
    positionB: "Other people's independent accounts are often more reliable evidence of what happened than your own memory.",
    tension: "first-person memory vs external corroboration",
    constructs: ["self-trust vs external evidence"],
    family: "AUTHORITY_VS_INDEPENDENCE",
    twinGroup: "TWIN_AUTHORITY",
  },
  {
    id: "d034",
    domain: "memory",
    positionA: "Revisiting and reinterpreting old memories in light of new understanding is a form of growth.",
    positionB: "Reinterpreting old memories to fit your current narrative is a way of rewriting the past to suit you.",
    tension: "reinterpretation as insight vs as distortion",
    constructs: ["narrative revision", "self-serving bias"],
    family: "PRESERVATION_VS_REVISION",
  },
  {
    id: "d035",
    domain: "memory",
    positionA: "Forgetting painful details over time is the mind protecting you.",
    positionB: "Forgetting painful details over time is the mind letting you avoid something you still need to face.",
    tension: "forgetting as protection vs avoidance",
    constructs: ["adaptive vs maladaptive forgetting"],
    family: "PROTECTION_VS_AVOIDANCE",
  },

  // ---------- uncertainty ----------
  {
    id: "d036",
    domain: "uncertainty",
    positionA: "When you don't know something important, you should say so plainly rather than guess.",
    positionB: "Refusing to offer any estimate under uncertainty is often less useful than a clearly-labeled guess.",
    tension: "abstaining vs estimating under uncertainty",
    constructs: ["calibrated guessing vs abstention"],
    family: "SUFFICIENCY_TO_COMMIT",
  },
  {
    id: "d037",
    domain: "uncertainty",
    positionA: "Living with an unresolved question is more honest than settling on a premature answer.",
    positionB: "Refusing to settle on any answer can become its own way of avoiding commitment.",
    tension: "preserving open questions vs avoiding decision",
    constructs: ["ambiguity tolerance", "decision avoidance"],
    family: "AMBIGUITY_VS_AVOIDANCE",
    twinGroup: "TWIN_AMBIGUITY_AVOIDANCE",
  },
  {
    id: "d038",
    domain: "uncertainty",
    positionA: "Probabilities should guide your decisions even about singular, one-off events.",
    positionB: "A probability calculated from many cases tells you little about what will happen in one specific case.",
    tension: "applying population statistics to a single instance",
    constructs: ["reference class problem"],
    family: "GENERAL_VS_PARTICULAR",
  },
  {
    id: "d039",
    domain: "uncertainty",
    positionA: "It's better to overprepare for unlikely bad outcomes than be caught without a plan.",
    positionB: "Constantly preparing for unlikely outcomes drains resources you need for the likely ones.",
    tension: "how much weight low-probability risks deserve",
    constructs: ["risk allocation"],
    family: "PROPORTIONALITY",
  },

  // ---------- decision-making ----------
  {
    id: "d040",
    domain: "decision-making",
    positionA: "The right decision-making process matters more than the outcome it happens to produce.",
    positionB: "A process that reliably produces bad outcomes isn't actually a good process, whatever its reputation.",
    tension: "process quality vs outcome quality as evaluation criteria",
    constructs: ["procedural vs outcome evaluation"],
    family: "PROCESS_VS_OUTCOME",
  },
  {
    id: "d041",
    domain: "decision-making",
    positionA: "Big decisions deserve a deliberate, structured process, not gut instinct.",
    positionB: "Instinct is often compressed experience, and can outperform slow deliberation on the decisions that matter most.",
    tension: "deliberation vs intuition for consequential choices",
    constructs: ["System 1 vs System 2"],
    family: "FEELING_VS_REASON",
    twinGroup: "TWIN_FEELING_REASON",
  },
  {
    id: "d042",
    domain: "decision-making",
    positionA: "Once you've made a decision, you should commit fully and stop second-guessing it.",
    positionB: "Treating a decision as unreviewable, even as new information arrives, is stubbornness, not commitment.",
    tension: "commitment vs revisability",
    constructs: ["reversibility"],
    family: "REVERSIBILITY_COMMITMENT",
    twinGroup: "TWIN_REVERSIBILITY",
  },
  {
    id: "d043",
    domain: "decision-making",
    positionA: "You should decide based on what you'd choose if you had to justify it to a stranger.",
    positionB: "Some decisions are legitimate precisely because they're personal and don't need to survive a stranger's scrutiny.",
    tension: "decisions justified by universal reasons vs by personal standing",
    constructs: ["impartial justification vs personal prerogative"],
    family: "UNIVERSAL_VS_PERSONAL",
  },
  {
    id: "d044",
    domain: "decision-making",
    positionA: "More options make for a better decision.",
    positionB: "Past a certain point, more options make decisions worse, not better.",
    tension: "where the value of additional options turns negative",
    constructs: ["threshold effects", "choice overload"],
    family: "DEPTH_THRESHOLD",
  },

  // ---------- social interpretation ----------
  {
    id: "d045",
    domain: "social interpretation",
    positionA: "You should interpret someone's ambiguous behavior in the most generous plausible way.",
    positionB: "Consistently choosing the most generous interpretation can blind you to a real pattern of harm.",
    tension: "charitable interpretation vs pattern recognition",
    constructs: ["principle of charity", "vigilance"],
    family: "TRUST_DEFAULT",
    twinGroup: "TWIN_TRUST_DEFAULT",
  },
  {
    id: "d046",
    domain: "social interpretation",
    positionA: "What someone says about their own motives is the best evidence of what those motives are.",
    positionB: "People are often unreliable narrators of their own motives; their behavior over time is better evidence.",
    tension: "self-report vs behavioral evidence for motive",
    constructs: ["self-report vs observed pattern"],
    family: "OBSERVATION_VS_INTERPRETATION",
  },
  {
    id: "d047",
    domain: "social interpretation",
    positionA: "Silence in a conversation usually means something is being withheld.",
    positionB: "Reading meaning into every silence says more about the interpreter's anxiety than the other person's intent.",
    tension: "inferring hidden meaning vs taking absence of signal as no signal",
    constructs: ["over-interpretation", "projection"],
    family: "SIGNAL_VS_NOISE",
  },
  {
    id: "d048",
    domain: "social interpretation",
    positionA: "If a group of people all interpret an event the same way, that interpretation is probably right.",
    positionB: "A shared interpretation can just as easily be a shared blind spot as it can be shared insight.",
    tension: "social consensus as evidence vs social consensus as bias",
    constructs: ["groupthink", "consensus as evidence"],
    family: "CONSENSUS_VS_PRECISION",
  },

  // ---------- responsibility ----------
  {
    id: "d049",
    domain: "responsibility",
    positionA: "People are responsible for their actions regardless of the circumstances that shaped them.",
    positionB: "Circumstances shape people so thoroughly that individual blame often misses where responsibility actually lies.",
    tension: "individual agency vs systemic/circumstantial causation",
    constructs: ["agency vs structure"],
    family: "INDIVIDUAL_VS_SYSTEM_RESPONSIBILITY",
    twinGroup: "TWIN_RESPONSIBILITY_SCOPE",
  },
  {
    id: "d050",
    domain: "responsibility",
    positionA: "If you contributed to a bad outcome even a little, you own a share of the responsibility for it.",
    positionB: "Diluting responsibility across everyone who contributed a little lets the primary cause off the hook.",
    tension: "distributed vs concentrated responsibility",
    constructs: ["proportional blame"],
    family: "PROPORTIONALITY",
  },
  {
    id: "d051",
    domain: "responsibility",
    positionA: "You're responsible for the effects of what you fail to do, not just what you actively do.",
    positionB: "Treating every omission as equivalent to an action makes responsibility limitless and unworkable.",
    tension: "acts vs omissions as grounds for responsibility",
    constructs: ["act/omission distinction"],
    family: "SCOPE_LIMITS",
  },
  {
    id: "d052",
    domain: "responsibility",
    positionA: "Apologizing requires acknowledging you were wrong.",
    positionB: "You can apologize for someone's pain without agreeing you were the one who caused it.",
    tension: "apology as admission of fault vs acknowledgment of impact",
    constructs: ["intent vs impact"],
    family: "INTENT_VS_OUTCOME",
  },

  // ---------- rules & exceptions ----------
  {
    id: "d053",
    domain: "rules & exceptions",
    positionA: "A rule that allows exceptions isn't really a rule.",
    positionB: "A rule that allows no exceptions will eventually produce an obviously unjust result.",
    tension: "whether rules must be exceptionless to function as rules",
    constructs: ["rule rigidity vs case sensitivity"],
    family: "RULE_VS_EXCEPTION",
  },
  {
    id: "d054",
    domain: "rules & exceptions",
    positionA: "You should follow the same standard for everyone, including yourself.",
    positionB: "You understand your own circumstances in a way you can't fully know for anyone else, which justifies treating your case differently.",
    tension: "universal standards vs first-person epistemic access",
    constructs: ["impartiality vs self-knowledge"],
    family: "UNIVERSAL_VS_PERSONAL",
  },
  {
    id: "d055",
    domain: "rules & exceptions",
    positionA: "Breaking a rule for a good reason still erodes the rule for everyone.",
    positionB: "Never breaking a rule for a good reason turns the rule into an idol more important than what it was meant to protect.",
    tension: "rule integrity vs the purpose behind the rule",
    constructs: ["letter vs spirit of a rule"],
    family: "LETTER_VS_SPIRIT",
  },

  // ---------- order & spontaneity ----------
  {
    id: "d056",
    domain: "order & spontaneity",
    positionA: "A well-ordered routine is what makes meaningful spontaneity possible.",
    positionB: "The more your life is structured by routine, the less room spontaneity actually has.",
    tension: "whether structure enables or crowds out spontaneity",
    constructs: ["structure as enabler vs constraint"],
    family: "STRUCTURE_VS_SPONTANEITY",
    twinGroup: "TWIN_STRUCTURE_SPONTANEITY",
  },
  {
    id: "d057",
    domain: "order & spontaneity",
    positionA: "Plans should be followed through once made, or making plans becomes pointless.",
    positionB: "A plan that can't yield to a better opportunity in the moment isn't serving you anymore.",
    tension: "commitment to a plan vs responsiveness to the moment",
    constructs: ["reversibility", "commitment"],
    family: "REVERSIBILITY_COMMITMENT",
    twinGroup: "TWIN_REVERSIBILITY",
  },
  {
    id: "d058",
    domain: "order & spontaneity",
    positionA: "Unpredictability keeps a shared life interesting.",
    positionB: "Reliability, not unpredictability, is what actually lets people feel safe enough to enjoy each other.",
    tension: "novelty vs reliability as the basis of a good shared life",
    constructs: ["novelty vs security"],
    family: "NOVELTY_VS_SECURITY",
  },

  // ---------- emotional reasoning ----------
  {
    id: "d059",
    domain: "emotional reasoning",
    positionA: "A strong emotional reaction is data worth taking seriously.",
    positionB: "A strong emotional reaction is often the least reliable moment to trust your own judgment.",
    tension: "emotion as signal vs emotion as noise in judgment",
    constructs: ["emotion as evidence"],
    family: "FEELING_VS_REASON",
    twinGroup: "TWIN_FEELING_REASON",
  },
  {
    id: "d060",
    domain: "emotional reasoning",
    positionA: "You should sit with a difficult feeling until you understand where it's coming from.",
    positionB: "Some difficult feelings don't need to be understood, just outlasted.",
    tension: "analysis vs endurance as a response to difficult emotion",
    constructs: ["insight-seeking vs distress tolerance"],
    family: "ANALYSIS_VS_ENDURANCE",
  },
  {
    id: "d061",
    domain: "emotional reasoning",
    positionA: "Being emotionally consistent, predictable to yourself and others, is a sign of maturity.",
    positionB: "Real emotional responsiveness means your reactions vary with context, not staying consistent for its own sake.",
    tension: "emotional consistency vs contextual responsiveness",
    constructs: ["consistency vs adaptability"],
    family: "CONTEXT_DEPENDENCE",
    twinGroup: "TWIN_CONTEXT_DEPENDENCE",
  },

  // ---------- aesthetics ----------
  {
    id: "d062",
    domain: "aesthetics",
    positionA: "A work's aesthetic value is independent of who made it or why.",
    positionB: "Knowing who made a work and why is part of what you're actually responding to.",
    tension: "the work itself vs its origin as the basis of aesthetic judgment",
    constructs: ["essentialism vs functionalism", "origin as meaning"],
    family: "FUNCTION_VS_ORIGIN",
    twinGroup: "TWIN_FUNCTION_ORIGIN",
  },
  {
    id: "d063",
    domain: "aesthetics",
    positionA: "Taste is largely learned, and disagreements about taste can in principle be resolved with enough shared context.",
    positionB: "Some disagreements about taste are genuinely irreducible, not just a shortage of shared context.",
    tension: "whether aesthetic disagreement is resolvable in principle",
    constructs: ["convergence vs pluralism"],
    family: "PRESERVE_CONTRADICTION_CANDIDATE",
  },
  {
    id: "d064",
    domain: "aesthetics",
    positionA: "Restoring an old work to its original condition honors it.",
    positionB: "Restoring an old work erases the history it accumulated, which was part of its value.",
    tension: "restoration as honoring origin vs erasing history",
    constructs: ["preservation vs revision"],
    family: "PRESERVATION_VS_REVISION",
  },

  // ---------- trust ----------
  {
    id: "d065",
    domain: "trust",
    positionA: "Trust should be extended gradually, in proportion to evidence of reliability.",
    positionB: "Waiting for full evidence before trusting anyone means never actually building deep trust with anyone.",
    tension: "when trust is sufficient without certainty",
    constructs: ["sufficiency vs completeness", "provisional commitment"],
    family: "SUFFICIENCY_TO_COMMIT",
    twinGroup: "TWIN_SUFFICIENCY",
  },
  {
    id: "d066",
    domain: "trust",
    positionA: "Once trust is broken, it can be fully rebuilt with enough consistent effort.",
    positionB: "Some breaches change the relationship permanently; the trust that's rebuilt is a different, more limited kind.",
    tension: "whether trust repair restores the original or creates something new",
    constructs: ["continuity vs discontinuity after rupture"],
    family: "CONTINUITY_VS_CHANGE_IDENTITY",
    twinGroup: "TWIN_CONTINUITY_IDENTITY",
  },
  {
    id: "d067",
    domain: "trust",
    positionA: "You should trust people at their word until they give you a specific reason not to.",
    positionB: "Trusting by default and only revising after harm means you always pay the cost of misplaced trust first.",
    tension: "the burden of proof in extending initial trust",
    constructs: ["default trust", "burden of proof"],
    family: "TRUST_DEFAULT",
    twinGroup: "TWIN_TRUST_DEFAULT",
  },

  // ---------- change & continuity ----------
  {
    id: "d068",
    domain: "change & continuity",
    positionA: "An institution should preserve the traditions that define its identity.",
    positionB: "An institution that refuses to change with the people it serves is preserving a shell, not an identity.",
    tension: "tradition as identity vs adaptation as survival",
    constructs: ["continuity vs adaptation"],
    family: "CONTINUITY_VS_CHANGE_IDENTITY",
    twinGroup: "TWIN_CONTINUITY_IDENTITY",
  },
  {
    id: "d069",
    domain: "change & continuity",
    positionA: "Gradual change is more durable than change forced through a sudden break.",
    positionB: "Some problems are structural enough that gradual change just delays the necessary break.",
    tension: "incrementalism vs rupture as the effective path to change",
    constructs: ["incrementalism vs discontinuity"],
    family: "INCREMENTAL_VS_RUPTURE",
  },
  {
    id: "d070",
    domain: "change & continuity",
    positionA: "You should finish what you start, even after your reasons for starting have changed.",
    positionB: "Continuing something only because you already started it is a trap, not a virtue.",
    tension: "sunk-cost continuation vs re-evaluation",
    constructs: ["sunk cost", "commitment vs revisability"],
    family: "REVERSIBILITY_COMMITMENT",
    twinGroup: "TWIN_REVERSIBILITY",
  },
];

// Sanity: ids must be unique.
(function assertUniqueIds() {
  const seen = new Set();
  for (const d of DILEMMAS) {
    if (seen.has(d.id)) throw new Error("Duplicate dilemma id: " + d.id);
    seen.add(d.id);
  }
})();
